# Generated by Django 5.0 on 2025-05-09 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, verbose_name="category uuid"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="category name")),
                (
                    "description",
                    models.CharField(
                        max_length=100, verbose_name="category description"
                    ),
                ),
                ("creation_time", models.TimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workout", "Workout"),
                            ("code", "Code"),
                            ("academic", "Academic"),
                            ("explore", "Explore"),
                        ],
                        default="NA",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="task uuid",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="task name")),
                (
                    "descripiton",
                    models.CharField(max_length=100, verbose_name="task description"),
                ),
                ("creation_time", models.TimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workout", "Workout"),
                            ("code", "Code"),
                            ("academic", "Academic"),
                            ("explore", "Explore"),
                        ],
                        default="NA",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objectives.category",
                    ),
                ),
            ],
        ),
    ]
