# Generated by Django 5.0 on 2025-05-12 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objectives", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AlterField(
            model_name="category",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("exercise", "Exercise"),
                    ("chores", "Chores"),
                    ("academic", "Academic"),
                    ("code", "Code"),
                    ("habit", "Habit"),
                    ("other", "Other"),
                ],
                default="NA",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                verbose_name="category uuid",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("exercise", "Exercise"),
                    ("chores", "Chores"),
                    ("academic", "Academic"),
                    ("code", "Code"),
                    ("habit", "Habit"),
                    ("other", "Other"),
                ],
                default="NA",
                max_length=30,
            ),
        ),
    ]
