# Generated by Django 5.0 on 2025-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objectives", "0002_remove_category_id_alter_category_creation_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
