# Generated by Django 5.0 on 2025-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objectives", "0003_category_status_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="category description",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="descripiton",
            field=models.CharField(
                max_length=100, null=True, verbose_name="task description"
            ),
        ),
    ]
