# Generated by Django 5.0 on 2025-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objectives", "0004_alter_category_description_alter_task_descripiton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="descripiton",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="task description"
            ),
        ),
    ]
